# Generated by Django 4.1.3 on 2022-11-14 13:28

import danceBattle.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True)),
                ('dancer1_move', models.CharField(blank=True, max_length=250)),
                ('dancer2_move', models.CharField(blank=True, max_length=250)),
                ('song', models.CharField(db_index=True, default=danceBattle.models.song_pick, max_length=50)),
                ('status', models.CharField(db_index=True, default='teaming', max_length=15, verbose_name='Dance Status')),
                ('match_start', models.DateTimeField(db_index=True, null=True, verbose_name='MatchStart')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('dancer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_profile1', to=settings.AUTH_USER_MODEL)),
                ('dancer2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dancer_profile2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
