# Generated by Django 4.1.3 on 2022-11-14 16:42

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('danceBattle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancestage',
            name='match_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True),
        ),
    ]
